from typing import Tuple

def width_vr_to_vl_h(mvr: float, theta: float, genl: int) -> float: ...
def width_vr_to_vl_z(mvr: float, theta: float, genl: int) -> float: ...
def width_vr_to_l_w(mvr: float, theta: float, genl: int) -> float: ...
def width_vr_to_vl_u_u(mvr: float, theta: float, genl: int, genq: int) -> float: ...
def width_vr_to_vl_d_d(mvr: float, theta: float, genl: int, genq: int) -> float: ...
def width_vr_to_l_u_d(mvr: float, theta: float, genl: int, genq: int) -> float: ...
def width_vr_to_vl_lp_lp(mvr: float, theta: float, genl: int, genlp: int) -> float: ...
def width_vr_to_vlp_lp_l(mvr: float, theta: float, genl: int, genlp: int) -> float: ...
def width_vr_to_vl_l_l(mvr: float, theta: float, genl: int) -> float: ...
def width_vr_to_vl_vl_vl(mvr: float, theta: float, genl: int) -> float: ...